FROM node:10.9.0-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install --loglevel error
RUN npm install dynamoose --save


# Bundle app source
COPY . /usr/src/app

EXPOSE 3000
CMD DEBUG=test:* npm start