AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A simple Hello World Serverless RESTful project
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: src/index.handler
      Timeout: 10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: any
        RedisPost:
          Type: Api
          Properties:
            Path: /counter
            Method: Post
        RedisGet:
          Type: Api
          Properties:
            Path: /counter
            Method: Get
